// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmY3Im-oorfOO7oEqb-5z2qEELsDpQIE4',
    appId: '1:1089459128319:web:21fb8ee7f8de8b184089ca',
    messagingSenderId: '1089459128319',
    projectId: 'shopsync-4f5bf',
    authDomain: 'shopsync-4f5bf.firebaseapp.com',
    storageBucket: 'shopsync-4f5bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM0ATsD7qph9SHIoc1S-t8L1CjBdIEfuI',
    appId: '1:1089459128319:android:106a177aac1122834089ca',
    messagingSenderId: '1089459128319',
    projectId: 'shopsync-4f5bf',
    storageBucket: 'shopsync-4f5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TvY9KqBmPhgZot1Ih4y1E4h_8Jy2rIU',
    appId: '1:1089459128319:ios:bffce3a0b102758e4089ca',
    messagingSenderId: '1089459128319',
    projectId: 'shopsync-4f5bf',
    storageBucket: 'shopsync-4f5bf.appspot.com',
    iosBundleId: 'com.example.shopSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TvY9KqBmPhgZot1Ih4y1E4h_8Jy2rIU',
    appId: '1:1089459128319:ios:bffce3a0b102758e4089ca',
    messagingSenderId: '1089459128319',
    projectId: 'shopsync-4f5bf',
    storageBucket: 'shopsync-4f5bf.appspot.com',
    iosBundleId: 'com.example.shopSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmY3Im-oorfOO7oEqb-5z2qEELsDpQIE4',
    appId: '1:1089459128319:web:7a6ef486c72218b84089ca',
    messagingSenderId: '1089459128319',
    projectId: 'shopsync-4f5bf',
    authDomain: 'shopsync-4f5bf.firebaseapp.com',
    storageBucket: 'shopsync-4f5bf.appspot.com',
  );
}
